const types = {
    SIGN_UP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_REQUEST_SUCCESS: 'SIGNUP_REQUEST_SUCCESS',
    SIGN_UP_REQUEST_FAIL: 'SIGN_UP_REQUEST_FAIL',
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    GET_STARSHIPS_SUCCESS: 'GET_STARSHIPS_SUCCESS',
    GET_STARSHIPS_FAIL: 'GET_STARSHIPS_FAIL',
};

export default types;
