const types = {
    SIGNUP_REQUEST_SUCCESS: 'SIGNUP_REQUEST_SUCCESS',
    SIGN_UP_REQUEST_FAIL: 'SIGN_UP_REQUEST_FAIL',
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
};

export default types;
